bar:
  height: 42
  location: top
  foreground: eeeeeeff
  background: 005577ff
  # margin: 8
  spacing: 5
  font: Hack Nerd Font Propo:pixelsize=26
  left:
    - dwl:
        anchors:
          - base: &dwl_base
              margin: 16
              conditions:
                id == 1: {string: {text: 1}}
                id == 2: {string: {text: 2}}
                id == 3: {string: {text: 3}}
                id == 4: {string: {text: 4}}
                id == 5: {string: {text: 5}}
                id == 6: {string: {text: 6}}
                id == 7: {string: {text: 7}}
                id == 8: {string: {text: 8}}
                id == 9: {string: {text: 9}}
        number-of-tags: 9
        dwl-info-filename: "/home/brian/.cache/dwl_info"
        content:
          list:
            items:
              - map:
                  conditions:
                    # default tag
                    id == 0: {string: {text: " {layout}  {title}", max: 35}}

                    urgent:
                      map:
                        <<: *dwl_base
                        deco: {background: {color: d08770ff}}
                    selected && ~empty:
                      map:
                        <<: *dwl_base
                        deco: {stack: [{background: {color: 005577ff}}, {underline: {size: 4, color: d8dee9ff}}]}
                    selected:
                      map:
                        <<: *dwl_base
                        deco: {stack: [{background: {color: 005577ff}}]}
                    empty:
                      map:
                        <<: *dwl_base
                        deco: {stack: [{background: {color: 222222ff}}]}
                    ~empty:
                      map:
                        <<: *dwl_base
                        deco: {stack: [{background: {color: 222222ff}}, {underline: {size: 4, color: d8dee9ff}}]}

  right:
    - network:
        name: wlp3s0
        content:
          string: {text: "[  {ssid}:{signal}dBm ]"}
    - cpu:
        poll-interval: 2500
        content:
          map:
            conditions:
              id < 0:
              - string: {text: "[  {cpu}% ]"}
    - mem:
        poll-interval: 2500
        content:
          string: {text: "[  {used:gb}/{total:gb}GB ]"}
    - pulse:
        content:
          map:
            conditions:
              ~sink_muted && ~source_muted:
                - string: {text: "[ 󰕾 {sink_percent}% ]"}
                # - string: {text: "mic: {source_percent}%"}
              ~sink_muted && source_muted:
                - string: {text: "[ 󰕾 {sink_percent}% ]"}
                # - string: {text: "mic: {source_percent}% (muted)"}
              sink_muted && ~source_muted:
                - string: {text: "[ 󰖁 {sink_percent}% ]"}
                # - string: {text: "mic: {source_percent}%"}
              sink_muted && source_muted:
                - string: {text: "[ 󰖁 {sink_percent}% ]"}
                # - string: {text: "mic: {source_percent}% (muted)"}
    - backlight:
        name: intel_backlight
        content:
          string: {text: "[ 󰃠 {percent}% ]"}
    - battery:
        name: BAT1
        content:
          map:
            default: {string: {text: "[ 󰁹 {capacity}% ]"}}
            conditions:
              state == charging: {string: {text: "[ 󰂄 {capacity}% ]", foreground: ffa600ff}}
              capacity <= 20: {string: {text: "[ 󰂃 {capacity}% ]", foreground: ff0000ff}}
    - clock:
        # date-format: "%m-%d"
        date-format: "%a %d %b %I:%M%p"
        content:
          - string: {on-click: gsimplecal, text: "[ {date} ]", right-margin: 15}
